In [1]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
# In case of errors, check if you are using the correct versions of the libraries. This notebook works on the following versions of libraries. Specify these versions if you get version related errors.
# TensorFlow version: 2.17.0
# Pandas version: 2.1.4
# NumPy version: 1.26.4
# Scikit-learn version: 1.5.2
# Keras version: 3.4.1

# print("TensorFlow version:", tf.__version__)
# print("Pandas version:", pd.__version__)
# print("NumPy version:", np.__version__)
# print("Scikit-learn version:", sklearn.__version__)
# print("Keras version:", tf.keras.__version__)

## Part 1: Import the Housing data and do feature transformations

In [3]:
df= pd.read_csv('house-price-full.csv')
df.head()

   bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [4]:
X = df.copy()
# Remove target
Y = X.pop('price')

# perform a scaler transform of the input data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# perform log transformation of target variable (For Sandeep: Is this needed?)
Y = np.log(Y)

In [5]:
df_scaled = pd.DataFrame(X)
df_scaled

            0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [6]:
Y

0      12.653958
1      14.684290
2      12.742566
3      12.948010
4      13.217674
         ...
494    13.380102
495    13.764217
496    12.128111
497    12.721886
498    12.254863
Name: price, Length: 499, dtype: float64

## Part 2: Create Model Using `keras`

![](multiple_neurons.png)

In [7]:
from tensorflow import keras

In [8]:
# model = keras.Sequential(
#     [
#         keras.layers.Dense(
#             2, activation="sigmoid", input_shape=(X.shape[-1],)
#         ),
#         keras.layers.Dense(1, activation="linear")
#     ]
# )
# model.summary()

# Newer versions of Keras support this:
model = keras.Sequential()
model.add(keras.layers.Input(shape=(X.shape[-1],)))
model.add(keras.layers.Dense(2, activation="sigmoid"))
model.add(keras.layers.Dense(1, activation="linear"))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

```python
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1,b1,w2,b2


def forward_prop(x, w1, b1, w2, b2):
    z1 = tf.matmul(x,w1) + b1
    h1 = tf.math.sigmoid(z1)
    z2 = tf.matmul(h1,w2) + b2
    h2 = z2
    return h2
```

In [9]:
model.compile(
    optimizer=keras.optimizers.SGD(), loss="mean_squared_error"
)

```python
def train(x, y, w1, b1, w2, b2):
    y_true = y
    with tf.GradientTape() as g:
        y_pred = forward_prop(x, w1, b1, w2, b2)

        # loss
        loss = 0.5*(y_true - y_pred)** 2
    
    #Gradient calculation  
    print("**************************************************")
    print("GRADIENTS")
    print("**************************************************")
    gw1, gb1, gw2, gb2 = g.gradient(loss, [w1, b1, w2, b2])
    print(" the gradient for 1st layer weights are:\n",gw1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer weights are:\n",gw2.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 1st layer bias are:\n",gb1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer bias are:\n",gb2.numpy())
    print("--------------------------------------------------")

    # Gradient descent:
    lr=0.2
    w1.assign_sub(lr*gw1)
    b1.assign_sub(lr*gb1)
    w2.assign_sub(lr*gw2)
    b2.assign_sub(lr*gb2)
    print("**************************************************")
    print("NEW UPDATES")
    print("**************************************************")
    print(" the updated 1st layer weights are:\n",w1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer weights are:\n",w2.numpy())
    print("--------------------------------------------------")
    print(" the updated 1st layer bias are:\n",b1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer bias are:\n",b2.numpy())


    return w1, b1, w2, b2,loss

```

In [10]:
model.fit(X,Y.values,epochs=10,batch_size=32)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 127.3859
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 46.1156
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.2135
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.0921
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8599
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4150
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3071
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2650
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2407
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2252

In [11]:
model.predict(X)[:,0]

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

array([12.969976 , 13.432357 , 13.033619 , 13.041074 , 13.304998 ,
       12.473629 , 12.524265 , 13.367651 , 13.086391 , 13.269356 ,
       13.010056 , 13.38414  , 13.075926 , 12.942593 , 13.389774 ,
       12.954671 , 12.994956 , 13.398839 , 12.973248 , 12.952478 ,
       13.066469 , 13.263313 , 13.014355 , 13.369232 , 13.276225 ,
       13.050627 , 13.079071 , 13.326542 , 13.384443 , 13.104077 ,
       13.272795 , 13.379455 , 13.294921 , 13.37632  , 13.438018 ,
       13.169428 , 12.465051 , 13.025074 , 13.036818 , 13.082211 ,
       12.9960375, 13.265906 , 12.470411 , 13.016502 , 12.509142 ,
       12.950284 , 13.037882 , 13.033619 , 12.962334 , 13.414089 ,
       13.367651 , 13.135978 , 13.115449 , 13.01972  , 13.34741  ,
       13.303325 , 13.325721 , 13.432918 , 12.967795 , 12.5546   ,
       13.414089 , 13.112353 , 13.369232 , 13.097851 , 13.38414  ,
       12.475776 , 13.003594 , 12.933779 , 12.669119 , 13.062254 ,
       13.353315 , 13.129839 , 13.333091 , 13.030418 , 12.968886 ,
       12.515619 , 13.324076 , 13.369232 , 13.319956 , 13.0926485,
       13.309173 , 13.44244  , 12.653803 , 13.01972  , 13.337977 ,
       12.606832 , 12.501593 , 12.985207 , 12.530756 , 12.508063 ,
       13.405567 , 13.058032 , 13.205824 , 13.078023 , 12.993875 ,
       13.379677 , 13.006826 , 13.400335 , 12.977602 , 13.4522915,
       13.404202 , 13.042137 , 12.968886 , 13.340414 , 13.324163 ,
       13.38336  , 13.31582  , 13.489069 , 12.469339 , 13.245012 ,
       13.258111 , 13.335537 , 12.938189 , 13.368247 , 13.310838 ,
       13.277161 , 13.065416 , 12.466123 , 13.406146 , 13.00575  ,
       13.307505 , 12.98195  , 13.35232  , 13.028282 , 13.028282 ,
       12.977602 , 13.265906 , 12.501593 , 13.032553 , 13.38336  ,
       13.169428 , 12.992792 , 13.337432 , 12.618834 , 12.569807 ,
       13.3347225, 13.01972  , 13.310838 , 13.018648 , 13.346076 ,
       13.034686 , 12.503749 , 13.420877 , 13.494647 , 12.995064 ,
       13.000359 , 12.977385 , 13.149219 , 13.478106 , 12.550259 ,
       13.346883 , 13.262447 , 12.497283 , 12.971067 , 13.32243  ,
       12.986292 , 13.041074 , 12.489747 , 12.456486 , 13.335548 ,
       12.9960375, 13.31913  , 13.250268 , 13.001438 , 13.41862  ,
       13.30081  , 13.269356 , 12.475776 , 12.938189 , 12.96124  ,
       13.233433 , 13.333906 , 13.375534 , 13.003594 , 13.002516 ,
       13.025074 , 13.310005 , 12.977602 , 13.267632 , 13.089522 ,
       12.933779 , 12.511301 , 13.337246 , 13.34927  , 13.346883 ,
       13.39807  , 13.314991 , 13.025074 , 13.296606 , 13.44611  ,
       12.978689 , 12.988461 , 13.054861 , 13.42762  , 13.001438 ,
       13.018648 , 13.310005 , 13.331457 , 13.392675 , 12.966703 ,
       13.456312 , 13.447575 , 13.397415 , 13.389774 , 13.142099 ,
       12.557856 , 13.40573  , 13.365274 , 12.957957 , 13.370022 ,
       13.419373 , 12.944792 , 13.321614 , 13.030418 , 12.478997 ,
       13.007904 , 12.978689 , 13.479163 , 13.038946 , 12.5048275,
       13.062254 , 12.910534 , 12.985207 , 13.388593 , 13.113385 ,
       13.4335   , 12.962334 , 13.478106 , 13.393448 , 12.951381 ,
       13.338058 , 12.931572 , 13.345269 , 13.497423 , 12.960146 ,
       12.99171  , 12.9981985, 12.944792 , 13.024004 , 13.095771 ,
       13.112353 , 12.152812 , 13.343653 , 13.286459 , 13.048507 ,
       13.0154295, 13.006826 , 12.545921 , 13.255936 , 13.295764 ,
       12.976513 , 13.027213 , 13.049822 , 12.490824 , 13.11648  ,
       12.933779 , 12.9960375, 13.358912 , 13.032553 , 13.078023 ,
       12.085168 , 13.35171  , 13.169428 , 13.089522 , 12.487596 ,
       12.467195 , 13.360338 , 13.016502 , 12.524265 , 13.036818 ,
       13.413711 , 12.654896 , 13.458826 , 13.335537 , 13.280499 ,
       13.362894 , 13.30081  , 13.061199 , 13.044262 , 13.069626 ,
       12.999279 , 12.460766 , 12.555685 , 13.001438 , 13.237882 ,
       13.141081 , 13.034686 , 12.977602 , 12.937086 , 12.467195 ,
       12.47685  , 12.933062 , 13.324899 , 12.9981985, 12.987376 ,
       12.969976 , 13.026144 , 13.097851 , 12.490824 , 12.974337 ,
       13.002516 , 13.395071 , 13.321606 , 13.0154295, 13.004672 ,
       13.022934 , 13.327362 , 13.266769 , 12.96124  , 13.466381 ,
       13.45776  , 12.502671 , 13.36337  , 13.359728 , 12.998846 ,
       12.467195 , 12.544837 , 13.050627 , 13.4044075, 13.287308 ,
       13.00575  , 13.354918 , 13.397415 , 12.960146 , 13.311669 ,
       13.3636875, 12.48437  , 13.036818 , 12.456486 , 12.525347 ,
       12.580684 , 13.320781 , 13.294077 , 12.616652 , 13.007904 ,
       13.034686 , 13.336351 , 13.314991 , 13.421629 , 13.330639 ,
       12.975426 , 12.492976 , 12.986292 , 13.349299 , 13.36156  ,
       13.066469 , 13.032553 , 13.02935  , 13.330639 , 12.515619 ,
       12.48222  , 13.412575 , 13.310005 , 12.488671 , 13.296606 ,
       13.038946 , 13.235413 , 12.511301 , 13.333091 , 13.086391 ,
       13.136999 , 13.333091 , 12.988461 , 12.927154 , 12.953575 ,
       12.966703 , 13.383254 , 13.014355 , 12.967795 , 13.347689 ,
       12.959051 , 12.96124  , 13.200726 , 13.451953 , 12.99171  ,
       12.545921 , 12.983036 , 12.975426 , 13.108219 , 12.997118 ,
       13.302487 , 13.042668 , 12.977602 , 12.49836  , 12.471483 ,
       13.073828 , 12.488671 , 12.48437  , 13.481341 , 13.002516 ,
       13.451224 , 13.373962 , 13.289003 , 13.261581 , 13.025074 ,
       12.48222  , 13.091607 , 13.446842 , 13.358912 , 12.975426 ,
       13.331457 , 13.348495 , 12.466123 , 13.280499 , 13.145153 ,
       12.456486 , 12.975426 , 12.981407 , 12.577419 , 13.051685 ,
       12.93929  , 12.987376 , 13.307505 , 12.977602 , 13.444644 ,
       13.325721 , 13.032553 , 12.950284 , 13.589266 , 13.310005 ,
       13.323501 , 13.422769 , 13.377889 , 12.502671 , 13.39807  ,
       12.978689 , 13.345269 , 13.304162 , 13.004672 , 12.976513 ,
       13.3636875, 13.310005 , 13.320781 , 12.971286 , 13.014355 ,
       13.354206 , 12.531837 , 13.304998 , 12.977602 , 12.9721575,
       12.9568615, 13.377104 , 13.449036 , 13.337165 , 13.201345 ,
       13.265043 , 13.394991 , 12.935985 , 13.304162 , 13.017576 ,
       13.041074 , 13.007904 , 13.51425  , 12.965611 , 13.342844 ,
       12.502671 , 13.335537 , 13.369232 , 13.377889 , 12.488671 ,
       12.969976 , 13.431346 , 13.612005 , 12.932455 , 13.398584 ,
       13.054861 , 13.352513 , 13.304998 , 12.971067 , 13.323254 ,
       12.973248 , 13.561498 , 13.377104 , 13.042137 , 13.413332 ,
       12.511301 , 13.011131 , 12.062537 , 12.993875 , 13.099928 ,
       13.513901 , 12.5102215, 13.432357 , 13.059088 , 13.354116 ,
       12.47685  , 13.3888035, 13.319956 , 13.425378 , 13.363997 ,
       13.062254 , 13.287308 , 13.136999 , 12.931572 , 13.393448 ,
       13.480219 , 12.973248 , 13.034686 , 12.937086 ], dtype=float32)